### ISSUE TITLE
Could not use with create react app - webpack issue

### ISSUE THREAD

**Issue by philholden** [gregberge/react-flatten-children#1]
Steps to repeat:

https://codesandbox.io/s/zl59mkk463

1. Click download code
2. extract zip
3. cd into dir
4. yarn install
5. npm start
6. view site in browse

Result:

```
TypeError: react_flatten_children__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function
```
As a temporary fix I can remove the `"module": "dist/index.mjs",` from `package.json` and package works.

**Comment by gregberge** [comment]
I am sorry but it should be something on your side, nobody has this problem and I never experienced it.
