### ISSUE TITLE
Add ability to flatten all children, not just fragments

### ISSUE THREAD

**Issue by kirill-konshin** [gregberge/react-flatten-children#8]

**Comment by gregberge** [comment]
Hello @kirill-konshin, I am sorry but what is the use-case? I am curious!

**Comment by kirill-konshin** [comment]
I was making a gatsby plug-in, to wrap some MDX images, so I need to create a wrapper that would grab transformed react elements and extract some of their props to process them. The problem is markup may change so easiest way is to flatten all children and just filter them.

**Comment by gregberge** [comment]
I think it is a very specific use-case. You should just copy the code of this repository in your project. I don't think it worth it to include it here and penalize every one (package size) for this use-case.

**Comment by kirill-konshin** [comment]
> penalize every one (package size) for this use-case

I've added 62 symbols.

The proposed functionality fits perfectly as you already recursively flatten the children, all I added is a flag to do this for all elements, not just fragments.

**Comment by gregberge** [comment]
I am sorry this is not a main "use-case", if someone asks again for it I will consider it.

**Comment by kirill-konshin** [comment]
Although I do understand that it's not a main use case, someone has already asked — me.

Addition perfectly fits in library name "react-flatten-children" — it produces flat array of all children.

I don't see any problems here, and reasons not to include... maintenance burden is not high. I can add tests if needed.

**Comment by gregberge** [comment]
@kirill-konshin your use-case is very very specific. You lose information by stripping components. The goal of this library is a "flattening", in a flattening, nothing is lost, it is just flattened. Your use-case is completely different! Anyway, I don't understand, what is the problem to just copy a small script in your code?

**Comment by kirill-konshin** [comment]
That’s exactly what I did, I copied. Anyway, I see you’re not willing to cooperate, so I’m done here.
